openapi: 3.0.3
components:
  schemas:
    PlacesSearchResponse:
      type: object
      required:
        - results
        - context
      properties:
        results:
          type: array
          items:
            $ref: '../schemas/place-search-schemas.yaml#/components/schemas/Place'
        context:
          $ref: '../schemas/place-search-schemas.yaml#/components/schemas/Context'
