openapi: 3.0.3
info:
  title: Foursquare Places API
  description: OpenAPI contract for the Foursquare Places Search endpoint. See https://docs.foursquare.com/fsq-developers-places/reference/places-api-overview
  version: v2025-06-17
servers:
- url: https://places-api.foursquare.com
  description: Foursquare Places API Server
security:
- bearerAuth: []
paths:
  /places/search:
    get:
      tags:
      - Places
      summary: Place Search
      description: "Search for places in the FSQ Places database using a location\
        \ and querying by name, category name, telephone number, taste label, or chain\
        \ name. For example, search for \"coffee\" to get back a list of recommended\
        \ coffee shops.\nYou may pass a location with your request by using one of\
        \ the following options. If none of the following options are passed, Place\
        \ Search defaults to geolocation using ip biasing with the optional radius\
        \ parameter.\nll & radius (circular boundary)\nnear (geocodable locality)\n\
        ne & sw (rectangular boundary)"
      operationId: placesSearch
      parameters:
      - name: X-Places-Api-Version
        in: header
        description: The version of the API to use.
        required: true
        schema:
          type: string
          default: v2025-06-17
      - name: query
        in: query
        description: "A string to be matched against all content for this place, including\
          \ but not limited to venue name, category, telephone number, taste, and\
          \ tips."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: ll
        in: query
        description: "The latitude/longitude around which to retrieve place information.\
          \ This must be specified as latitude,longitude (e.g., ll=41.8781,-87.6298)."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: radius
        in: query
        description: "Sets a radius distance (in meters) used to define an area to\
          \ bias search results. The maximum allowed radius is 100,000 meters. Radius\
          \ can be used in combination with ll or ip biased geolocation only. By using\
          \ radius, global search results will be omitted. If not provided, default\
          \ radius applied is 22000 meters."
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: fsq_category_ids
        in: query
        description: "Filters the response and returns FSQ Places matching the specified\
          \ categories. Supports multiple Category IDs, separated by commas. For a\
          \ complete list of Foursquare Category IDs, refer to the Category Taxonomy\
          \ page."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: fsq_chain_ids
        in: query
        description: "Filters the response and returns FSQ Places matching the specified\
          \ chains. Supports multiple chain IDs, separated by commas. For more information\
          \ on Foursquare Chain IDs, refer to the Chains page."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: exclude_fsq_chain_ids
        in: query
        description: "Filters the response and returns FSQ Places not matching any\
          \ of the specified chains. Supports multiple chain IDs, separated by commas.\
          \ Cannot be used in conjunction with exclude_all_chains. For more information\
          \ on Foursquare Chain IDs, refer to the Chains page."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: exclude_all_chains
        in: query
        description: Filters the response by only returning FSQ Places that are not
          known to be part of any chain. Cannot be used in conjunction with exclude_chains.
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: fields
        in: query
        description: "Indicate which fields to return in the response, separated by\
          \ commas. If no fields are specified, all Pro Fields are returned by default.\
          \ For a complete list of returnable fields, refer to the Places Response\
          \ Fields page."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: min_price
        in: query
        description: "Restricts results to only those places within the specified\
          \ price range. Valid values range between 1 (most affordable) to 4 (most\
          \ expensive), inclusive."
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: max_price
        in: query
        description: "Restricts results to only those places within the specified\
          \ price range. Valid values range between 1 (most affordable) to 4 (most\
          \ expensive), inclusive."
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: open_at
        in: query
        description: "Support local day and local time requests through this parameter.\
          \ To be specified as DOWTHHMM (e.g., 1T2130), where DOW is the day number\
          \ 1-7 (Monday = 1, Sunday = 7) and time is in 24 hour format.  Places that\
          \ do not have opening hours will not be returned if this parameter is specified.\
          \ Cannot be specified in conjunction with open_now."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: open_now
        in: query
        description: Restricts results to only those places that are open now. Places
          that do not have opening hours will not be returned if this parameter is
          specified. Cannot be specified in conjunction with open_at.
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: tel_format
        in: query
        description: "Specifies the format of the returned telephone number. Possible\
          \ values are: national (default), e164."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: ne
        in: query
        description: The latitude/longitude representing the north/east points of
          a rectangle. Must be used with sw parameter to specify a rectangular search
          box. Global search results will be omitted.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: sw
        in: query
        description: The latitude/longitude representing the south/west points of
          a rectangle. Must be used with ne parameter to specify a rectangular search
          box. Global search results will be omitted.
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: near
        in: query
        description: "A string naming a locality in the world (e.g., \"Chicago, IL\"\
          ). If the value is not geocodable, returns an error. Global search results\
          \ will be omitted."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: sort
        in: query
        description: "Specifies the order in which results are listed. Possible values\
          \ are: relevance (default), rating, distance"
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: limit
        in: query
        description: "The number of results to return, up to 50. Defaults to 10."
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: A list of places matching the search criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlacesSearchResponse'
        "400":
          description: Invalid request
        "401":
          description: Unauthorized - API key missing or invalid
        "429":
          description: Rate limit exceeded
        "500":
          description: Internal server error
components:
  schemas:
    Attributes:
      type: object
      properties:
        restroom:
          type: object
          additionalProperties: true
        outdoor_seating:
          type: object
          additionalProperties: true
        atm:
          type: object
          additionalProperties: true
        has_parking:
          type: object
          additionalProperties: true
        wifi:
          type: object
          additionalProperties: true
        delivery:
          type: object
          additionalProperties: true
        reservations:
          type: object
          additionalProperties: true
        takes_credit_card:
          type: object
          additionalProperties: true
    Category:
      type: object
      properties:
        fsq_category_id:
          type: string
        name:
          type: string
        icon:
          $ref: '#/components/schemas/Photo'
    Center:
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
    Chain:
      type: object
      properties:
        fsq_chain_id:
          type: string
        name:
          type: string
        logo:
          $ref: '#/components/schemas/Photo'
        parent_id:
          type: string
    Circle:
      type: object
      properties:
        center:
          $ref: '#/components/schemas/Center'
        radius:
          type: integer
          format: int32
    Context:
      type: object
      properties:
        geo_bounds:
          $ref: '#/components/schemas/GeoBounds'
    ExtendedLocation:
      type: object
      properties:
        dma:
          type: string
        census_block_id:
          type: string
    GeoBounds:
      type: object
      properties:
        circle:
          $ref: '#/components/schemas/Circle'
    Hours:
      type: object
      properties:
        display:
          type: string
        is_local_holiday:
          type: boolean
        open_now:
          type: boolean
        regular:
          type: array
          items:
            $ref: '#/components/schemas/RegularHours'
    Location:
      type: object
      properties:
        address:
          type: string
        locality:
          type: string
        region:
          type: string
        postcode:
          type: string
        admin_region:
          type: string
        post_town:
          type: string
        po_box:
          type: string
        country:
          type: string
        formatted_address:
          type: string
    Photo:
      type: object
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        prefix:
          type: string
        suffix:
          type: string
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        classifications:
          type: array
          items:
            type: string
        tip:
          $ref: '#/components/schemas/PhotoTip'
    PhotoTip:
      type: object
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date-time
        text:
          type: string
        url:
          type: string
        photo:
          type: string
        lang:
          type: string
        agree_count:
          type: integer
        disagree_count:
          type: integer
    Place:
      type: object
      properties:
        fsq_place_id:
          type: string
        latitude:
          type: object
          additionalProperties: true
        longitude:
          type: object
          additionalProperties: true
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        chains:
          type: array
          items:
            $ref: '#/components/schemas/Chain'
        date_closed:
          type: string
          format: date-time
        date_created:
          type: string
          format: date-time
        date_refreshed:
          type: string
          format: date-time
        description:
          type: string
        distance:
          type: integer
          format: int32
        email:
          type: string
        extended_location:
          $ref: '#/components/schemas/ExtendedLocation'
        attributes:
          $ref: '#/components/schemas/Attributes'
        hours:
          $ref: '#/components/schemas/Hours'
        hours_popular:
          type: array
          items:
            $ref: '#/components/schemas/RegularHours'
        link:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        menu:
          type: string
        name:
          type: string
        photos:
          type: array
          items:
            $ref: '#/components/schemas/Photo'
        popularity:
          type: number
          format: double
        related_places:
          type: array
          items:
            $ref: '#/components/schemas/RelatedPlace'
        social_media:
          $ref: '#/components/schemas/SocialMedia'
        stats:
          $ref: '#/components/schemas/Stats'
        store_id:
          type: string
        tastes:
          type: array
          items:
            type: string
        tel:
          type: string
        tips:
          type: array
          items:
            $ref: '#/components/schemas/PhotoTip'
        verified:
          type: boolean
        unresolved_flags:
          type: array
          items:
            type: string
        veracity_rating:
          type: object
          additionalProperties: true
        website:
          type: string
    PlacesSearchResponse:
      required:
      - context
      - results
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/Place'
        context:
          $ref: '#/components/schemas/Context'
    RegularHours:
      type: object
      properties:
        close:
          type: string
        day:
          type: integer
          format: int32
        open:
          type: string
    RelatedPlace:
      type: object
      properties:
        parent:
          $ref: '#/components/schemas/Place'
        children:
          type: array
          items:
            $ref: '#/components/schemas/Place'
    SocialMedia:
      type: object
      properties:
        facebook_id:
          type: string
        instagram:
          type: string
        twitter:
          type: string
    Stats:
      type: object
      properties:
        total_photos:
          type: integer
          format: int32
        total_ratings:
          type: integer
          format: int64
        total_tips:
          type: integer
          format: int32
  parameters:
    apiVersion:
      name: X-Places-Api-Version
      in: header
      description: The version of the API to use.
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: v2025-06-17
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
